version: "3.9"

services:
  db:
    image: mariadb:11.8
    container_name: transaction_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: transactiondb
      MARIADB_USER: app
      MARIADB_PASSWORD: app123
      MARIADB_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uapp", "-papp123"]
      interval: 5s
      timeout: 3s
      retries: 20
